### ISSUE TITLE
Image Magick Version >=6.8 check not sufficient

### ISSUE THREAD

**Issue by remi10001** [mauvilsa/textfeats#1]
Could you state the specific ImageMagick version that works with textFeats? The package checks for ImageMagick version >=6.8. I have the following version, but it does not allow textFeats to make:

Version: ImageMagick 6.8.2-10 2018-04-06 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2013 ImageMagick Studio LLC
Features: DPC OpenMP
Delegates: bzlib djvu mpeg fontconfig freetype jbig jng jp2 jpeg lcms lqr lzma openexr png ps tiff x zlib

When I run make, this ImageMagick API appears different from that required by textFeats:

Scanning dependencies of target textFeats
[ 14%] Building CXX object CMakeFiles/textFeats.dir/log.cc.o
[ 28%] Building CXX object CMakeFiles/textFeats.dir/TextFeatExtractor.cc.o
/deep_data/textFeats/TextFeatExtractor.cc: In member function ‘void TextFeatExtractor::preprocess(Magick::Image&, std::vector<cv::Point_<int> >*, bool)’:
/deep_data/textFeats/TextFeatExtractor.cc:1670:9: error: ‘class Magick::Image’ has no member named ‘morphology’
     tmp.morphology( Magick::DilateMorphology, string(kern) );
         ^
/deep_data/textFeats/TextFeatExtractor.cc:1670:21: error: ‘DilateMorphology’ is not a member of ‘Magick’
     tmp.morphology( Magick::DilateMorphology, string(kern) );
                     ^
/deep_data/textFeats/TextFeatExtractor.cc:1670:21: note: suggested alternative:
In file included from /usr/local/include/ImageMagick/magick/accelerate.h:25:0,
                 from /usr/local/include/ImageMagick/magick/MagickCore.h:64,
                 from /usr/local/include/ImageMagick/Magick++/Include.h:41,
                 from /usr/local/include/ImageMagick/Magick++.h:9,
                 from /deep_data/textFeats/TextFeatExtractor.h:18,
                 from /deep_data/textFeats/TextFeatExtractor.cc:9:
/usr/local/include/ImageMagick/magick/morphology.h:77:3: note:   ‘DilateMorphology’
   DilateMorphology,             /* Maximum Value in Neighbourhood */
   ^
/deep_data/textFeats/TextFeatExtractor.cc: In member function ‘void TextFeatExtractor::estimateAngles(Magick::Image&, float*, float*, float)’:
/deep_data/textFeats/TextFeatExtractor.cc:1723:14: error: ‘class Magick::Image’ has no member named ‘deskew’
     desloped.deskew( 0.4*QuantumRange );
              ^
/deep_data/textFeats/TextFeatExtractor.cc:1726:29: error: ‘class Magick::Image’ has no member named ‘artifact’
     vslope = stof( desloped.artifact("deskew:angle") );
                             ^
CMakeFiles/textFeats.dir/build.make:86: recipe for target 'CMakeFiles/textFeats.dir/TextFeatExtractor.cc.o' failed
make[2]: *** [CMakeFiles/textFeats.dir/TextFeatExtractor.cc.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/textFeats.dir/all' failed
make[1]: *** [CMakeFiles/textFeats.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

Thank you for your help

**Comment by mauvilsa** [comment]
Could you please give some details about the environment where you are trying to run this. What OS? How did you install ImageMagick?

**Comment by remi10001** [comment]
Thank you very much for the quick response. My OS is:

Ubuntu 16.04.4 LTS (GNU/Linux 4.15.0-46-generic x86_64)

I installed ImageMagick from source in April 2018. It passes all tests in make check. Here is the output of:  identify -list configure

Path: /usr/local/lib/ImageMagick-6.8.2//config-Q16/configure.xml

Name           Value
-------------------------------------------------------------------------------
CC             gcc
CFLAGS         -I/usr/include/OpenEXR -I/usr/include/lqr-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -fopenmp -g -O2 -Wall -pthread -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16
CODER_PATH     /usr/local/lib/ImageMagick-6.8.2/modules-Q16/coders
CONFIGURE      ./configure
CONFIGURE_PATH /usr/local/etc/ImageMagick/
COPYRIGHT      Copyright (C) 1999-2013 ImageMagick Studio LLC
CPPFLAGS       -I/usr/local/include/ImageMagick
CXX            g++
CXXFLAGS       -g -O2 -pthread
DEFS           -DHAVE_CONFIG_H
DELEGATES      bzlib djvu mpeg fontconfig freetype jbig jng jp2 jpeg lcms lqr lzma openexr png ps tiff x zlib
DISTCHECK_CONFIG_FLAGS --disable-deprecated --with-quantum-depth=16 --with-umem=no --with-autotrace=no --with-gslib=no --with-fontpath= --with-gvc=no --with-rsvg=no --with-wmf=no --with-perl=no
DOCUMENTATION_PATH /usr/local/share/doc/ImageMagick-6.8.2
EXEC-PREFIX    /usr/local
EXECUTABLE_PATH /usr/local/bin
FEATURES       DPC OpenMP
FILTER_PATH    /usr/local/lib/ImageMagick-6.8.2/modules-Q16/filters
HOST           x86_64-unknown-linux-gnu
INCLUDE_PATH   /usr/local/include/ImageMagick
LDFLAGS        -L/usr/local/lib
LIB_VERSION    0x682
LIB_VERSION_NUMBER 6,8,2,10
LIBRARY_PATH   /usr/local/lib/ImageMagick-6.8.2
LIBS           -lMagickCore -ljbig -llcms2 -ltiff -lfreetype -ljasper -ljpeg -llqr-1 -lglib-2.0 -lpng12 -ldjvulibre -lfontconfig -lfreetype -lXext -lXt -lSM -lICE -lX11 -llzma -lbz2 -lIlmImf -lImath -lHalf -lIex -lIexMath -lIlmThread -lpthread -lz -lm -lgomp -lpthread
NAME           ImageMagick
PCFLAGS        -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16
PREFIX         /usr/local
QuantumDepth   16
RELEASE_DATE   2018-04-06
SHARE_PATH     /usr/local/share/ImageMagick-6.8.2
SHAREARCH_PATH /usr/local/lib/ImageMagick-6.8.2/config-Q16
SVN_REVISION   11005
TARGET_CPU     x86_64
TARGET_OS      linux-gnu
TARGET_VENDOR  unknown
VERSION        6.8.2
WEBSITE        http://www.imagemagick.org

Path: [built-in]

Name           Value
-------------------------------------------------------------------------------
FEATURES       OpenMP
NAME           ImageMagick
QuantumDepth   16

**Comment by mauvilsa** [comment]
@remi10001 you are right. According to ImageMagick changelog, morphology is only available in magick++ since version 6.8.8. I have updated the cmake requirement to ImageMagick++>=6.8.9 since this is the default version that comes with Ubuntu 16.04, with which textFeats has been mostly tested.
